# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Unblock Bluetooth on startup (rfkill may block it)
exec-once = rfkill unblock bluetooth

# Load all plugins
exec-once = solaar --window=hide
