# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Lazy Git, exec, omarchy-launch-tui lazygit -p $(grep -A 1 "recentrepos:" ~/.local/state/lazygit/state.yml | tail -1 | sed 's/^[[:space:]]*-[[:space:]]*//')
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"

# Layout switch
bindd = SUPER, R, Switch to scrolling layout, layoutmsg, setlayout scrolling
bindd = SUPER, D, Switch to Dwindle (Default) layout, layoutmsg, setlayout dwindle

# Overwrite existing bindings
unbind = SUPER, SPACE
bindd = SUPER, SPACE, Switch keybord layout, exec, ~/.local/bin/notify-layout.sh
bindd = ALT, SPACE, Launch apps, exec, omarchy-launch-walker

unbind = SUPER ALT, SPACE
bindd = SUPER, grave, Omarchy menu, exec, omarchy-menu

unbind = SUPER, W
bindd = SUPER, Q, Close window, killactive,

unbind = SUPER, S
bindd = SUPER, E, Toggle scratchpad, togglespecialworkspace, scratchpad
unbind = SUPER ALT, S
bindd = SUPER ALT, E, Move window to scratchpad, movetoworkspacesilent, special:scratchpad

bindd = SUPER, S, Universal save, sendshortcut, CTRL, S,
bindd = SUPER, Z, Universal undo, sendshortcut, CTRL, Z,
bindd = SUPER, A, Universal select all, sendshortcut, CTRL, A,

unbind = SUPER, BACKSPACE
bindd = SUPER, BACKSPACE, Toggle all workspace view, hyprexpo:expo, toggle

# I don't want to toggle waybar
unbind = SUPER SHIFT, SPACE
