# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 5
    # gaps_out = 5

    # Use master layout instead of dwindle
    # layout = master

    # Dynamic layouts configurable for each workspace
    layout = workspacelayout
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 5
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

plugin {
  wslayout {
    default_layout=dwindle
  }
  hyprscrolling {
      column_width = 0.6
      fullscreen_on_one_column = true
  }
  hyprexpo {
    columns = 3
    gap_size = 5
    bg_col = rgb(111111)
    workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1

    gesture_distance = 300 # how far is the "max" for the gesture
  }
}
