# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # Gaps between windows
    gaps_in = 1
    gaps_out = 3

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 5

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

plugin {
  wslayout {
    default_layout=dwindle
  }
  hyprscrolling {
      column_width = 0.6
      fullscreen_on_one_column = true
  }
  hyprexpo {
    columns = 3
    gap_size = 5
    bg_col = rgb(111111)
    workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1

    gesture_distance = 300 # how far is the "max" for the gesture
  }
}

# Disble opacity by default
windowrule = opacity 1.0 1.0, match:class .*
