# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,2

# PC
monitor = HDMI-A-2, 3840x2160@30, auto, 2 # External LG for PC

# Slimbook
monitor = eDP-1, 2880x1800@120, 0x180, 2 # Built-in
monitor = DP-1, 3840x2160@60, 1440x0, 2 # External LG

# failback
monitor = ,preferred,auto,2 # Any other monitor

# Workspace assignments
# When external LG is connected, use it as default for workspaces 1-5
# Workspace 6 stays on built-in monitor

# Slimbook default workspaces
workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:eDP-1, default:true
